report-job-status: mask backticks in commit msg
When a commit message had backticks inside, we had the syntax err in JS
due to substituting expression ${{ github.event.head_commit.message }}:

    SyntaxError: Unexpected identifier
        <...>
    Error: Unhandled error: SyntaxError: Unexpected identifier

Now we have a special preparation step where all backticks in the commit
message are masked to avoid this issue.